name: size
on: [pull_request]
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: andresz1/size-limit-action@v1
        build_script: yarn apollo-codegen && yarn build
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
